// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ping.proto

#include "ping.pb.h"
#include "ping.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace vl {

static const char* Ping_method_names[] = {
  "/vl.Ping/ping",
};

std::unique_ptr< Ping::Stub> Ping::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Ping::Stub> stub(new Ping::Stub(channel));
  return stub;
}

Ping::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_ping_(Ping_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Ping::Stub::ping(::grpc::ClientContext* context, const ::vl::PingRequest& request, ::vl::PingResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ping_, context, request, response);
}

void Ping::Stub::experimental_async::ping(::grpc::ClientContext* context, const ::vl::PingRequest* request, ::vl::PingResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ping_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::vl::PingResponse>* Ping::Stub::AsyncpingRaw(::grpc::ClientContext* context, const ::vl::PingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::vl::PingResponse>::Create(channel_.get(), cq, rpcmethod_ping_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::vl::PingResponse>* Ping::Stub::PrepareAsyncpingRaw(::grpc::ClientContext* context, const ::vl::PingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::vl::PingResponse>::Create(channel_.get(), cq, rpcmethod_ping_, context, request, false);
}

Ping::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Ping_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Ping::Service, ::vl::PingRequest, ::vl::PingResponse>(
          std::mem_fn(&Ping::Service::ping), this)));
}

Ping::Service::~Service() {
}

::grpc::Status Ping::Service::ping(::grpc::ServerContext* context, const ::vl::PingRequest* request, ::vl::PingResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace vl

